# Generated by Django 4.0.5 on 2022-06-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_reasons_alter_project_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='reason',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Reasons',
        ),
    ]
