# Generated by Django 4.0.4 on 2022-06-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_department_user_remove_project_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(default='In Progress', max_length=255),
        ),
    ]
