# Generated by Django 4.0.4 on 2022-06-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='status',
            field=models.CharField(default='In Progress', max_length=255),
        ),
    ]
