# Generated by Django 4.0.5 on 2022-06-07 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_tache_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tache',
            old_name='status',
            new_name='statut',
        ),
    ]
